version: '3.1'
services:
  websvr:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./services/websvr/default.conf:/etc/nginx/conf.d/default.conf
      - ./services/websvr/public:/usr/share/nginx/html
    depends_on:
      - appsvr
  appsvr:
    build: 
      context: ./services/appsvr
      dockerfile: Dockerfile
    volumes:
      - ./dev-res:/appsvr
      - .:/root/workspace
      - ~/.gitconfig:/root/.gitconfig
    ports:
      - 9000
    depends_on:
      - db
    command: tail -f > /dev/null
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydic
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    volumes:
      - ./services/db/data:/var/lib/mysql
      - ./services/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./services/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
